# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0009_auto_20161228_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=300)),
                ('menu_title', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30)),
                ('template', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
