# Generated by Django 2.1.5 on 2019-02-02 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0010_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='type',
            field=models.CharField(choices=[('Experience', 'Experience'), ('Presentation', 'Presentation'), ('Workshop', 'Workshop'), ('Publication', 'Publication'), ('Education', 'Education'), ('Award', 'Award'), ('Course', 'Course'), ('Conference', 'Conference')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, default=None, upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tracker_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date tracked'),
        ),
    ]
