# Generated by Django 2.2.10 on 2020-02-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0013_auto_20200226_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
