# Generated by Django 2.2.10 on 2020-02-28 07:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0014_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
