# Generated by Django 2.2.13 on 2020-12-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0015_auto_20200228_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='file',
            field=models.FileField(blank=True, default=None, upload_to='files'),
        ),
    ]
