# Generated by Django 5.1.3 on 2024-11-16 14:39

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0017_auto_20201228_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField(blank=True, default=None, null=True)),
                ('order_by', models.IntegerField(default=0)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='consult.cv')),
            ],
        ),
    ]
