# Generated by Django 5.1.3 on 2024-11-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0018_cvskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvskill',
            name='cv',
        ),
    ]
