# Generated by Django 5.1.3 on 2024-11-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0019_remove_cvskill_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvskill',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
