# Generated by Django 5.1.3 on 2024-11-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0020_cvskill_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvskill',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
