# Generated by Django 5.2.6 on 2025-09-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0021_alter_cvskill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
