

def is_search_crawler(user_agent):
    spiders = ('bot',
               'crawl',
               'slurp',
               'spider',
               'archiver',
               'facebook',
               'lycos',
               'scooter',
               'altavista',
               'teoma',
               'domainreanimator.com',
               'python-urllib',
               'yandeximages',
               'plukkie',
               'buzzsumo',
               'clickagy',
               'kraken',
               'wotbox',
               'nutch',
               'contextad',
               'pinterest',
               'deusu',
               'go-http-client',
               'yeti',
               'ltx71',
               'qwantify',
               'teoma',
               'alexa',
               'froogle',
               'gigabot',
               'inktomi',
               'looksmart',
               'url_spider_sql',
               'firefly',
               'nationaldirectory',
               'ask jeeves',
               'tecnoseek',
               'infoseek',
               'webfindbot',
               'girafabot',
               'crawler',
               'www.galaxy.com',
               'googlebot',
               'googlebot/2.1',
               'webmaster',
               'scooter',
               'james bond',
               'slurp',
               'msnbot',
               'appie',
               'fast',
               'webbug',
               'spade',
               'zyborg',
               'rabaz',
               'baiduspider',
               'feedfetcher-google',
               'technoratisnoop',
               'rankivabot',
               'mediapartners-google',
               'sogou web spider',
               'webalta crawler',
               'mj12bot',
               'yandex/',
               'yadirectbot',
               'stackrambler',
               'dotbot',
               'updown.io daemon 2.6')
    if user_agent.lower() in spiders:
        return True
    return False
